# -*- coding: utf-8 -*-
"""fibanocci.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19x4YLVDpkk6C90EcJA583VbQ8kBH1CHr
"""

# printing fibnocci numbers

a, b = 0,1
print(a)
while b < 100:
  print (b)
  a , b = b , a+b

# n fibnocci numbers
n = 15
a , b = 0,1
print(a,end = " ")
count = 1
while count < n:
    a , b = b, a+b
    print(b,end = " ")
    count+=1

#nth finanocci number
n = 15
a , b = 0,1
count = 1
while count < n:
    a , b = b, a+b
    count+=1
print(b,end = " ")

def fib(n):
  if n == 0:
    return 0
  if n == 1:
    return 1
  return fib(n-1)+fib(n-2)

fib(34)

